server:
  port: 8085

spring:
  profiles:
    active: dev
  application:
    name: UReport
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp12hhva25ukb6wo56o.mysql.rds.aliyuncs.com:3306/cloud?serverTimezone=GMT%2B8&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    username: cloudadmin
    password: Huangyi2015